# SUPERTREND Example

In [8]:
import polars as pl

from bartons.indicators import SUPERTREND
from bartons.samples import sample_prices

In [9]:
prices = sample_prices("daily", max_bars=250)
prices

shape: (250, 6)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┐
│ date       ┆ open       ┆ high       ┆ low        ┆ close      ┆ volume    │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│ date       ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ i64       │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╡
│ 2023-08-14 ┆ 177.268901 ┆ 178.982126 ┆ 176.611497 ┆ 178.753036 ┆ 43675600  │
│ 2023-08-15 ┆ 178.175305 ┆ 178.772932 ┆ 176.352513 ┆ 176.750931 ┆ 43622600  │
│ 2023-08-16 ┆ 176.432212 ┆ 177.836645 ┆ 175.804689 ┆ 175.87442  ┆ 46964900  │
│ 2023-08-17 ┆ 176.442174 ┆ 176.810712 ┆ 172.796589 ┆ 173.314545 ┆ 66062900  │
│ 2023-08-18 ┆ 171.621237 ┆ 174.41021  ┆ 171.28258  ┆ 173.802612 ┆ 61114200  │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         │
│ 2024-08-05 ┆ 199.089996 ┆ 213.5      ┆ 196.0      ┆ 209.270004 ┆ 119548600 │
│ 2024-08-06 ┆ 205.300003 ┆ 209.990005 ┆ 201.070007 ┆ 207.229996 ┆ 69660500  │
│ 2024-08-07 ┆ 206.899994 ┆ 213.639999 ┆ 206.389999 ┆ 209.820007 ┆ 63516400  │
│ 2024-08-08 ┆ 213.110001 ┆ 214.199997 ┆ 208.830002 ┆ 213.309998 ┆ 47161100  │
│ 2024-08-09 ┆ 212.100006 ┆ 216.779999 ┆ 211.970001 ┆ 216.240005 ┆ 42171700  │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┘

In [10]:
prices.with_columns(
    SUPERTREND(10, 3.0)
).unnest()

shape: (250, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ date       ┆ open       ┆ high       ┆ low       ┆ close     ┆ volume    ┆ supertren ┆ direction │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ d         ┆ ---       │
│ date       ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ i64       ┆ ---       ┆ i64       │
│            ┆            ┆            ┆           ┆           ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2023-08-14 ┆ 177.268901 ┆ 178.982126 ┆ 176.61149 ┆ 178.75303 ┆ 43675600  ┆ null      ┆ null      │
│            ┆            ┆            ┆ 7         ┆ 6         ┆           ┆           ┆           │
│ 2023-08-15 ┆ 178.175305 ┆ 178.772932 ┆ 176.35251 ┆ 176.75093 ┆ 43622600  ┆ null      ┆ null      │
│            ┆            ┆            ┆ 3         ┆ 1         ┆           ┆           ┆           │
│ 2023-08-16 ┆ 176.432212 ┆ 177.836645 ┆ 175.80468 ┆ 175.87442 ┆ 46964900  ┆ null      ┆ null      │
│            ┆            ┆            ┆ 9         ┆           ┆           ┆           ┆           │
│ 2023-08-17 ┆ 176.442174 ┆ 176.810712 ┆ 172.79658 ┆ 173.31454 ┆ 66062900  ┆ null      ┆ null      │
│            ┆            ┆            ┆ 9         ┆ 5         ┆           ┆           ┆           │
│ 2023-08-18 ┆ 171.621237 ┆ 174.41021  ┆ 171.28258 ┆ 173.80261 ┆ 61114200  ┆ null      ┆ null      │
│            ┆            ┆            ┆           ┆ 2         ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-08-05 ┆ 199.089996 ┆ 213.5      ┆ 196.0     ┆ 209.27000 ┆ 119548600 ┆ 226.94526 ┆ -1        │
│            ┆            ┆            ┆           ┆ 4         ┆           ┆ 3         ┆           │
│ 2024-08-06 ┆ 205.300003 ┆ 209.990005 ┆ 201.07000 ┆ 207.22999 ┆ 69660500  ┆ 226.94526 ┆ -1        │
│            ┆            ┆            ┆ 7         ┆ 6         ┆           ┆ 3         ┆           │
│ 2024-08-07 ┆ 206.899994 ┆ 213.639999 ┆ 206.38999 ┆ 209.82000 ┆ 63516400  ┆ 226.94526 ┆ -1        │
│            ┆            ┆            ┆ 9         ┆ 7         ┆           ┆ 3         ┆           │
│ 2024-08-08 ┆ 213.110001 ┆ 214.199997 ┆ 208.83000 ┆ 213.30999 ┆ 47161100  ┆ 226.94526 ┆ -1        │
│            ┆            ┆            ┆ 2         ┆ 8         ┆           ┆ 3         ┆           │
│ 2024-08-09 ┆ 212.100006 ┆ 216.779999 ┆ 211.97000 ┆ 216.24000 ┆ 42171700  ┆ 226.94526 ┆ -1        │
│            ┆            ┆            ┆ 1         ┆ 5         ┆           ┆ 3         ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘