In [ ]:
import polars as pl
import minimal_plugin as mp

from polars.testing import assert_frame_equal

In [12]:
df = pl.DataFrame(
    {
        "a": [1, 2, 3, 4, None, 5],
        "b": [1, 1, 1, 2, 2, 2],
    }
)
df

shape: (6, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ i64  ┆ i64 │
╞══════╪═════╡
│ 1    ┆ 1   │
│ 2    ┆ 1   │
│ 3    ┆ 1   │
│ 4    ┆ 2   │
│ null ┆ 2   │
│ 5    ┆ 2   │
└──────┴─────┘

In [13]:
result = df.with_columns(a_cum_sum=mp.cum_sum("a"))
result

shape: (6, 3)
┌──────┬─────┬───────────┐
│ a    ┆ b   ┆ a_cum_sum │
│ ---  ┆ --- ┆ ---       │
│ i64  ┆ i64 ┆ i64       │
╞══════╪═════╪═══════════╡
│ 1    ┆ 1   ┆ 1         │
│ 2    ┆ 1   ┆ 3         │
│ 3    ┆ 1   ┆ 6         │
│ 4    ┆ 2   ┆ 10        │
│ null ┆ 2   ┆ null      │
│ 5    ┆ 2   ┆ 15        │
└──────┴─────┴───────────┘

In [14]:
result = df.with_columns(a_cum_sum=mp.cum_sum("a").over("b"))
result

shape: (6, 3)
┌──────┬─────┬───────────┐
│ a    ┆ b   ┆ a_cum_sum │
│ ---  ┆ --- ┆ ---       │
│ i64  ┆ i64 ┆ i64       │
╞══════╪═════╪═══════════╡
│ 1    ┆ 1   ┆ 1         │
│ 2    ┆ 1   ┆ 3         │
│ 3    ┆ 1   ┆ 6         │
│ 4    ┆ 2   ┆ 4         │
│ null ┆ 2   ┆ null      │
│ 5    ┆ 2   ┆ 9         │
└──────┴─────┴───────────┘