In [1]:
import polars as pl

from bartons import plugin
from bartons.ema import EMA


print("ok")

ok

In [2]:
df = pl.DataFrame(
    {
        "a": [1, 2, 3, 4, None, 5],
        "b": [1, 1, 1, 2, 2, 2],
    }
)
print(df)

s = pl.Series([1.0, 2.0, 3.0, 4.0, None, 5.0])
print(s)

shape: (6, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ i64  ┆ i64 │
╞══════╪═════╡
│ 1    ┆ 1   │
│ 2    ┆ 1   │
│ 3    ┆ 1   │
│ 4    ┆ 2   │
│ null ┆ 2   │
│ 5    ┆ 2   │
└──────┴─────┘
shape: (6,)
Series: '' [f64]
[
	1.0
	2.0
	3.0
	4.0
	null
	5.0
]

In [3]:
result = df.with_columns(EMA(pl.col("a"), period=3).alias("ema_a"))
result

shape: (6, 3)
┌──────┬─────┬───────┐
│ a    ┆ b   ┆ ema_a │
│ ---  ┆ --- ┆ ---   │
│ i64  ┆ i64 ┆ f64   │
╞══════╪═════╪═══════╡
│ 1    ┆ 1   ┆ null  │
│ 2    ┆ 1   ┆ null  │
│ 3    ┆ 1   ┆ 2.25  │
│ 4    ┆ 2   ┆ 3.125 │
│ null ┆ 2   ┆ null  │
│ 5    ┆ 2   ┆ null  │
└──────┴─────┴───────┘

In [4]:
result = df.with_columns(pl.col("a").bt.ema(period=3).alias("ema_a"))
result

shape: (6, 3)
┌──────┬─────┬───────┐
│ a    ┆ b   ┆ ema_a │
│ ---  ┆ --- ┆ ---   │
│ i64  ┆ i64 ┆ f64   │
╞══════╪═════╪═══════╡
│ 1    ┆ 1   ┆ null  │
│ 2    ┆ 1   ┆ null  │
│ 3    ┆ 1   ┆ 2.25  │
│ 4    ┆ 2   ┆ 3.125 │
│ null ┆ 2   ┆ null  │
│ 5    ┆ 2   ┆ null  │
└──────┴─────┴───────┘

In [5]:
plugin.ema(s)

shape: (6,)
Series: 'ema' [f64]
[
	null
	null
	null
	null
	null
	null
]

In [6]:
plugin.__all__

['__version__', 'ema']

In [7]:
plugin.ema

In [8]:
dir(plugin.ema)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [9]:
plugin.ema.__text_signature__

'(series, *, period=20)'

In [10]:
plugin.ema.__module__

'bartons.plugin'

In [11]:
import inspect

inspect.signature(plugin.ema)